# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{uploadable_file}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nick Zalabak"]
  s.date = %q{2010-08-31}
  s.description = %q{Makes ordinary files act like a multipart file if uploaded in a form, works well with attachment libraries like
    paperclip, attachment_fu, etc}
  s.email = %q{techwhizbang@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/uploadable_file.rb",
     "test/bowling.zip",
     "test/dilbert.jpg",
     "test/helper.rb",
     "test/test_uploadable_file.rb",
     "test/text.txt",
     "uploadable_file.gemspec"
  ]
  s.homepage = %q{http://github.com/techwhizbang/uploadable_file}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple wrapper around a Tempfile that adds content_type and original file name}
  s.test_files = [
    "test/helper.rb",
     "test/test_uploadable_file.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mime-types>, [">= 1.16"])
      s.add_development_dependency(%q<shoulda>, [">= 2.11.3"])
    else
      s.add_dependency(%q<mime-types>, [">= 1.16"])
      s.add_dependency(%q<shoulda>, [">= 2.11.3"])
    end
  else
    s.add_dependency(%q<mime-types>, [">= 1.16"])
    s.add_dependency(%q<shoulda>, [">= 2.11.3"])
  end
end

